version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "02:00"
      timezone: UTC
    commit-message:
      prefix: "chore"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "02:00"
      timezone: UTC
    commit-message:
      prefix: "ci"
